# Generated by Django 2.2.6 on 2019-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_app', '0003_auto_20191014_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_email',
            field=models.EmailField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
